# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 647)
        MainWindow.setMinimumSize(QtCore.QSize(647, 647))
        MainWindow.setMaximumSize(QtCore.QSize(647, 647))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 171, 51))
        self.label.setObjectName("label")
        
        #exponents radio button
        self.exponents_button = QtWidgets.QRadioButton(self.centralwidget)
        self.exponents_button.setGeometry(QtCore.QRect(250, 110, 81, 21))
        self.exponents_button.setObjectName("exponents_button")
        
        #cat ears radio button
        self.cat_ears_button = QtWidgets.QRadioButton(self.centralwidget)
        self.cat_ears_button.setGeometry(QtCore.QRect(50, 110, 71, 21))
        self.cat_ears_button.setObjectName("cat_ears_button")
        
        #alien ears radio button
        self.alien_ears_button = QtWidgets.QRadioButton(self.centralwidget)
        self.alien_ears_button.setGeometry(QtCore.QRect(470, 110, 95, 20))
        self.alien_ears_button.setObjectName("alien_ears_button")
        
        #prompt for first input line
        self.input_line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line1.setGeometry(QtCore.QRect(210, 250, 191, 21))
        self.input_line1.setObjectName("input_line1")
        self.input_line1.hide()
        
        #prompt for second input line
        self.input_line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line2.setGeometry(QtCore.QRect(210, 290, 191, 21))
        self.input_line2.setObjectName("input_line2")
        self.input_line2.hide()
        
        #label explaining the operation
        self.explanation_label = QtWidgets.QLabel(self.centralwidget)
        self.explanation_label.setGeometry(QtCore.QRect(160, 140, 291, 91))
        self.explanation_label.setText("")
        self.explanation_label.setObjectName("explanation_label")
        
        #label prompting user to enter file name to store data to
        self.file_name_label = QtWidgets.QLabel(self.centralwidget)
        self.file_name_label.setGeometry(QtCore.QRect(160, 330, 301, 101))
        self.file_name_label.setText("")
        self.file_name_label.setObjectName("file_name_label")
        
        #input field for file name
        self.file_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.file_name_input.setGeometry(QtCore.QRect(250, 440, 113, 21))
        self.file_name_input.setObjectName("file_name_input")
        self.file_name_input.hide()
        
        #submit button
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(170, 520, 93, 28))
        self.submit_button.setObjectName("submit_button")
        self.submit_button.hide()
        
        #button to confirm which operation the user wants done
        self.confirm_button = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_button.setGeometry(QtCore.QRect(240, 140, 131, 28))
        self.confirm_button.setObjectName("confirm_button")
        
        #label for first operation input line
        self.input_line1_label = QtWidgets.QLabel(self.centralwidget)
        self.input_line1_label.setGeometry(QtCore.QRect(110, 250, 81, 16))
        self.input_line1_label.setText("")
        self.input_line1_label.setObjectName("input_line1_label")
        self.input_line1_label.hide()
        
        #label for second operation input line
        self.input_line2_label = QtWidgets.QLabel(self.centralwidget)
        self.input_line2_label.setGeometry(QtCore.QRect(110, 290, 81, 16))
        self.input_line2_label.setText("")
        self.input_line2_label.setObjectName("input_line2_label")
        self.input_line2_label.hide()


        #restart button
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setGeometry(QtCore.QRect(350, 520, 93, 28))
        self.restart_button.setObjectName("restart_button")
        self.restart_button.hide()

        #used to display error if error occurs
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(470, 250, 121, 61))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Improved Recursion Program"))
        self.exponents_button.setText(_translate("MainWindow", "Exponents"))
        self.cat_ears_button.setText(_translate("MainWindow", "Cat Ears"))
        self.alien_ears_button.setText(_translate("MainWindow", "Alien Ears"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.confirm_button.setText(_translate("MainWindow", "Confrim Selection"))
        self.restart_button.setText(_translate("MainWindow", "Restart"))

